import React from 'react';
import { Helmet } from 'react-helmet';

const Code = () => {
    return (
        <div className="lg:px-20 lg:py-16 md:px-10 pb-8 px-8 bg-black">
                  <Helmet>
        <meta charSet="utf-8" />
        <title>Brainzeo | Code of Conduct</title>
        <link rel="canonical" href="https://www.brainzeo.tech/code" />
      </Helmet>
            <div className="footer-container py-4 mx-auto">
                <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
                    <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-cyan">Code of Conduct</h1>
                    <div className="h-1 w-20 bg-cyan rounded"></div>
                </div>
            </div>
            <div className="leading-8 text-gray-100">
                <p>Sorting Brainzeo (the “organisation”) owns and operates the website <a href="#" className='text-cyan'>brainzeo.co</a> and mobile application (together “Brainzeo Platform” or “Brainzeo”). Brainzeo Platform is an online education platform that supports and facilitates the online creation of educational videos/or tutorials by the users who wish to be educators on Brainzeo Platform. Brainzeo offers both live and recorded classes for free and via subscription. Brainzeo also offers its iconic Learners live mentorship sessions with their Educators for doubt clearing, strategy & study plan and concept clarity as part of the iconic subscription.</p>
                <p>Considering the possible interactions between the Learners (who may be minors i.e., under the age of 18 years) and you, the Company realizes the need to implement specific guidelines that govern your conduct on the Brainzeo Platform while interacting with Learners (including Minors). Protecting the safety and well-being of children is of utmost importance to the Company and hence the Company has adopted this Minor Interaction - Code of Conduct Guidelines (“Minor & Learner Interaction Guidelines”) requiring Educators/Mentors/other users to conduct themselves with utmost care while interacting with minors on the Brainzeo Platform and take reasonable measures to ensure the safety of such minors.</p>
                <p>This Minor & Learner Interaction guideline aims to define and lay down the expectations on behaviour and your actions while interacting with minors on Brainzeo. Additionally, it will lay down the scope of application of this Minor & Learner Interaction Guidelines and guidelines for reporting any issues relating to minors.</p>
                <p>Please read this Minor & Learner Interaction Guidelines, along with the Privacy Policy, Terms and Conditions, User Guidelines, and all terms and conditions, rules and policies made available or published on Brainzeo Platform as they shall govern your use of the Brainzeo Platform. By using or visiting the Brainzeo Platform or any Brainzeo software, data feeds, and service provided to you on, from, or through the Brainzeo Platform, you signify your agreement to </p>
                <ol className="list-roman">
                    <li>this Minor & Learner Interaction Guidelines; </li>
                    <li>the “Terms and Conditions”, </li>
                    <li>Brainzeo’s Privacy Policy and any other terms that are updated and uploaded on the Brainzeo Platform from time to time. If you do not agree to any of these terms, please do not use the Brainzeo Platform.</li>
                </ol>
                <ol className="list-alpha ">
                    <li>
                <h4 className="text-cyan lg:text-2xl md:text-2xl text-xl font-medium py-4">Definitions</h4>
                        <ol className="list-decimal">
                            <li>“Educators” shall mean and include all users who are teaching or tutoring on the Brainzeo platform.</li>
                            <li>“Learners” shall mean and include all users (including Minors) who have subscribed to or otherwise using Brainzeo as a learning platform.</li>
                            <li>“Mentors” shall mean and include all users who are providing the mentoring services on the Brainzeo platform to the Learners who have subscribed to such services or otherwise.</li>
                            <li>“Minor/s” or “Child/Children” shall mean and be construed in accordance with the Indian Majority Act, 1875, the Protection of Children against Sexual Offences Act, 2012 (POCSO Act, 2012), Child Labour (Prohibition and Regulation) Act, 1986 and such other applicable Indian laws i.e., the term shall mean and include all individuals who have not attained the age of 18 (eighteen) years.</li>
                            <li>“Minor & Learner Interaction Guidelines” shall mean this Minor & Learner Interaction - Code of Conduct Guidelines, on Brainzeo platform and includes all annexures and appendices attached thereto, if any and updates, changes and amendment as may be made by the Company and uploaded herein, from time to time.</li>
                            <li>“You” or “You’re” shall mean Educator, Learner, Mentors or any other Users of the Brainzeo Platform.</li>
                        </ol>
                    </li>
                    <li>
                        <h4 className="text-cyan lg:text-2xl md:text-2xl text-xl font-medium py-4">SCOPE OF APPLICATION</h4>
                        <p>This Minor & Learner Interaction Guidelines shall apply to all Educators, Mentors and any user on the Brainzeo Platform, who interact with Minors on or through any feature on the Brainzeo platform.</p>
                        <p>All Educators, Mentors, Learners and any other users interacting with Minors, in any capacity, on or through any feature on the Brainzeo Platform shall adhere to this Minor & Learner Interaction Guidelines. Any violation of this Minor & Learner Interaction Guidelines amounts to termination of your account, subscription or agreement with the Company, as the case may be and the Company also reserves the right to initiate appropriate legal proceedings against you if it deems necessary.</p>
                    </li>
                    <li>
                        <h4 className="text-cyan lg:text-2xl md:text-2xl text-xl font-medium py-4">Rules of Conduct</h4>
                        <ol className="list-decimal">
                            <li>No Discrimination: Treat every Minor with empathy and respect, regardless of his/her race, colour, gender, sexuality, language, religion, religious belief, heritage, political/another opinion, national/ethnic/social origin or property/disability/birth/another status; listen to them and respect their views.</li>
                            <li>Conducive Learning Environment: Establish an atmosphere that fosters the development of Minor through your actions and words. Do not place a Minor at risk of harm or abuse and do not harm or abuse any Minor in any manner whatsoever, including but not limited to emotionally or sexually.</li>
                            <li>Appropriate Communication and Behaviour: Good communication is the vehicle for learning and essential for the further development of Minor. Good communication involves listening and talking in ways that Minors understand and feel heard, important and valued. Using any form of language or behaviour towards Minor that is inappropriate, demotivating, harassing, abusive, sexually provocative, demeaning, intimidating, offensive, discriminatory or culturally insensitive shall not be tolerated; further, any communication or behaviour while interacting with Minor shall not, in any manner whatsoever, induce or support physical or sexual relationships with Minor or portray the use of or encourage the use of alcohol, drugs, cigarettes or other intoxicating or restricted substances. The Company understands that there may be instances when there are the exchange of ideas and opinions which is essential in the learning process, while it is agreed that individuals have the right to voice their opinions, the Company has zero tolerance towards any form of communication or behaviour stated hereinabove and the Company –
                                <ol>
                                    <li>DOES NOT encourage or tolerate any form of hate speech or statements that are libellous, slanderous, threatening, violent, predatory, defamatory, or any statement that incites hatred against specific individuals or groups with respect to but not limited to race or ethnic origin, country caste, religion, disability, gender, age, sexual orientation/gender identity etc.; and</li>
                                    <li>DOES NOT tolerate any form of harassment or bullying on the Brainzeo Platform and strive to keep the platform a safe space to foster learning. Harassment, in this case, would include, without limitation, abusive videos, comments, messages, revealing someone’s personal information, including sensitive personally identifiable information of individuals, content or comments uploaded in order to humiliate someone, sexual harassment or sexual bullying in any form.</li>
                                </ol>
                            </li>
                            <li>If it comes to the notice of the Company that your actions towards a Minor are inappropriate in any manner, then the Company reserves the right to take immediate and necessary actions, as it deems fit including legal proceeding, against you.</li>
                            <li>Content Sharing: Your interaction with a Minor on Brainzeo should be specific to the purpose of your engagement with such Minor and accordingly, information shared with such Minor should be strictly applicable and relatable to the subject matter being discussed between you and the Minor. Sharing and display of inappropriate content with/to the Minor including but not limited to materials encouraging crime, violence, terrorism, racism, sexism, self-harm, suicide, cruelty, pornography, gambling, or any content whose sole objective is to sensationalize, shock or disturb individuals (electronically or in any other form) is not allowed and shall not be tolerated.</li>
                            <li>Recording of the interactions with Minor: Unless recording is done by the Brainzeo Platform as part of the Brainzeo Platform offering, you shall not record or otherwise store the interaction and/or sessions between you and the Minor and/or their parents/legal guardian including through the use of a secondary camera or any other recording devices.</li>
                            <li>Impersonation: Educators/Mentors/other users having entered into an agreement with the Company to teach or otherwise use Brainzeo to communicate with, the Learners (including Minors) are bound to fulfil their obligations in person (i.e., by themselves) and not assign or sublicense the same to another person. Educator/Mentor/such other user engaging any other individual/person to impersonate them or an Educator/Mentor/such other user impersonating as another Educator/Mentor/another user, while teaching or otherwise using Brainzeo to communicate/interact with the Learners (including Minors) is not permitted and shall not be tolerated and considered a violation of this Minor & Learner Interaction Guidelines. In this case, impersonation would mean the intention to cause confusion regarding who the real person is by pretending to be them (such as user names, image, documents, certificates etc., not belonging to or not used to identify the intended Educator/Mentor/another user, or pretending to be a company, institute, group etc., by using their logo, brand name or any distinguishing mark).</li>
                            <li>Confidentiality: Company understands that during the interactions between you and the Learners (including Minors), you may be privy to certain personal information about Learners (including Minors) or their parents/guardians. Hence, you shall at all times maintain the confidentiality of such information received and ensure that such information is dispensed to only those individuals who are legitimately entitled to strictly in accordance with their agreement with the Company and Brainzeo’s terms and condition and policies (including its Privacy Policy) is available on Company’s website.</li>
                            <li>Relationship with the Learners (including Minors): The relationship between you and the Learners will be strictly limited to the purpose of imparting education or knowledge, or for such purpose as specifically stated in the agreement or terms of engagement communicated to you by the Company and you shall not form any relationship or arrangement (financial or otherwise) with the Learner (including Minors or their parents/legal guardians) which could in any way be deemed to be exploitative or abusive. Do not use child labour in any form.</li>
                            <li>Being Safe Online: Not everything online is trustworthy. Hence, if you are using online resources to create your teaching or reference materials that are to be shared with the Learners and/or Minors (including downloading of any content or files relevant to the subject being discussed with the Learners and/or Minors), it is important that you assess the reliability of such resources and the information provided therein. Prior to using any such online resources or platforms, it is aly recommended that you exercise reasonable caution and read the terms and conditions for the use of such sources as provided on the platforms. Further, you must understand the importance of safeguarding your computers, laptops or any other handheld device used by you to access the Brainzeo Platform and interact with the Learners (including Minors) from virus attacks, trojans and phishing attacks; because such attacks will not only threaten your privacy but may also expose the Learners and their privacy to such attacks when any form communication/interaction takes place through such compromised device.</li>
                            <li>Training Sessions: If there are any training sessions and workshops conducted by the Company, you must attend the same and ensure to implement the lessons learned from such sessions and workshops during your interactions with Learners. Further, the Company encourages you to attend training sessions and workshops conducted by other organizations to better understand the acceptable standards of conduct while interacting with Minors (whether online or offline), however, before implementing any of the lessons learnt from such sessions or workshops, you shall consult with the Company.</li>
                        </ol>
                    </li>
                    <li>
                        <h4 className="text-cyan lg:text-2xl md:text-2xl text-xl font-medium py-4">Child Abuse and Punishments</h4>
                        <p>Apart from the prohibited activities stated in the ‘Rules of Conduct’ section above, it is important for you to understand that Child abuse in any form (physical, emotional, or sexual) and in any manner (including through online platforms) could be punishable under the Indian Laws and you are strictly prohibited from engaging in such activities in any manner whatsoever.</p>
                        <p>To help you better understand online Child abuse and its consequences, the concepts and the relative punishments under certain applicable laws are briefly detailed below for their immediate reference. However, it is aly recommended that you do further research and read through all the applicable laws in relation to the treatment of Minors/Children, including the links provided herein. Further, the Company shall endeavour to update the Policy from time to time depending on any changes to the existing laws and regulations, however, it shall be your responsibility to keep yourself updated about the applicable laws and regulations from time to time.</p>
                        <ol className="list-decimal">
                            <li>What Constitutes Child Abuse?
                                Child abuse or maltreatment constitutes all forms of physical and/or emotional ill-treatment, sexual abuse, neglect or negligent treatment or commercial or other exploitation, resulting in actual or potential harm to the child’s health, survival, development or dignity in the context of a relationship of responsibility, trust or power.
                                <ol className="list-decimal">
                                    <li>Physical abuse: The intentional use of physical force against a child that results in or has a high likelihood of resulting in harm to the child’s health, survival, development or dignity. This includes hitting, beating, kicking, shaking, biting, strangling, scalding, burning, poisoning and suffocating.</li>
                                    <li>Emotional/mental abuse: Emotional abuse includes the failure to provide a developmentally appropriate, supportive environment so that the child can develop a stable and full range of emotional and social competencies proportionate with his or her personal potential and in the context of the society in which the Child dwells. Acts include restriction of movement, patterns of belittling, denigrating, scapegoating, threatening, scaring, discriminating, ridiculing or other non-physical forms of hostile or rejecting treatment.</li>
                                    <li>Neglect and negligent treatment: Neglect is the failure on the part of the parents, guardian, teacher/educators/mentors, or another responsible party to provide for the Child’s basic needs, such as food, shelter, medical care, education opportunities, or protection and supervision. It is abuse through omission of the necessary environment and resources for the child to reach their full potential; and the act of not recognizing physical or emotional abuse.</li>
                                    <li>Exploitation: Commercial or other exploitation of a Child refers to use of the Child in work or other activities for the benefit of others. This includes, but is not limited to, Child labour and Child prostitution. These activities are to the detriment of the Child’s physical or mental health, education, or spiritual, moral or social-emotional development. The Child Labour (Prohibition and Regulation) Act, 1986 and the Protection of Children from Sexual Offences Act, 2012 address the issues concerning Child labour and sexual abuse, and any act under in relation to that is deemed a punishable offence under the said regulations.</li>
                                    <li>Sexual abuse: Sexual abuse is an act or behaviour which constitutes a sexual offence under the Protection of Children from Sexual Offences Act, 2012 (‘POCSO Act, 2012’), as amended from time to time. Such sexual offences include penetrative sexual assault (including rape), non-penetrative sexual assault (including touching the private parts of a Child), sexual harassment (including stalking a Child, showing a Child pornography, online grooming, and making a Child exhibit his/her body) and using a Child for pornographic purposes (including storing of pornographic material involving a Child for commercial purposes).
                                        An abetment of and even an attempt to commit a sexual offence under the POCSO Act, 2012 are also considered to be offences. Certain offences under the POCSO, 2012 are considered to be aggravated offences and are subject to stringent punishments.
                                    </li>
                                </ol>
                            </li>
                            <li>
                                Legal Implications of Online Child Abuse:
                                This Minor and Learner Interaction guideline has only highlighted a few circumstances of Child Abuse and the legal implications thereto with an intention to give you a brief insight on the probable consequences of mis-utilizing the Brainzeo Platform. Hence, you must not consider the information provided in this Minor and Learner Interaction Guidelines as the ultimate source of information relating to Child Abuse and its legal implications. It is aly recommended that they keep themselves updated about the applicable laws and regulations from time to time.
                                <ol className="list-decimal">
                                    <li>Juvenile Justice (Care and Protection of Children) Act, 2015: It is to be noted that the Juvenile Justice (Care and Protection of Children) Act, 2015 criminalizes acts that may cause a child mental or physical suffering. As per section 75 of the Act, whoever, having the actual charge of, or control over, a Child, assaults, abandons, abuses, exposes or willfully neglects the Child or causes or procures the Child to be assaulted, abandoned, abused, exposed or neglected in a manner likely to cause such Child unnecessary mental or physical suffering, shall be punishable with imprisonment for a term which may extend to three years or with fine of one lakh rupees or with both.</li>
                                    <li>Sexual Harassment: POCSO Act, 2012 recognizes sexual harassment as a punishable offence; ‘Sexual Harassment as per Section 11 of the POCSO Act, 2012 is an act of a person done/committed with a sexual intent and such acts include –
                                        <ol className="list-decimal">
                                            <li>3.	The provisions of the Information Technology Act are not gender specific and apply to everyone.</li>
                                            <li>making a Child exhibit his/her body or any part of his/her body so as it is seen by such person or any other person, or showing any object to a Child in any form or media for pornographic purposes; or</li>
                                            <li>repeatedly or constantly following or watching or contacting a Child either directly or through electronic, digital or any other means; or</li>
                                            <li>threatening to use, in any form of media, a real or fabricated depiction through electronic, film or digital or any other mode, of any part of the body of the Child or the involvement of the child in a sexual act; or</li>
                                            <li>enticing a child for pornographic purposes or gives gratification, therefore.</li>
                                        </ol>
                                    </li>
                                    <li>Section 12 of the POCSO Act, 2012 states that an act of sexual harassment upon a Child shall be punished with either imprisonment for a term up to three years or fine or both.</li>
                                    <li>Voyeurism and violation of privacy:
                                        <ol className="list-decimal">
                                            <li>Section 354C, the Indian Penal Code (IPC) 1860 states that viewing and/or capturing the image of a girl or woman going about her private acts, where she thinks that no one is watching her, is a crime. The offender in such cases of voyeurism can be punished with three to seven years of imprisonment and a fine. While this section of the IPC can only be used by girls and women, the Information Technology Act, 2000 is gender neutral.</li>
                                            <li>Section 66E, IT Act, 2000: Intentionally or knowingly capturing, publishing or transmitting the image of a private area of any person without his or her consent, under circumstances violating the privacy of that person, shall be punished with imprisonment which may extend to three years or with fine not exceeding Rupees two lakh or with both.</li>
                                        </ol>
                                    </li>
                                    <li>Sending obscene material without the consent of the recipient:
                                        <ol className="list-decimal">
                                            <li>Section 67, IT Act, 2000: It punishes sharing obscene material in electronic form. The punishment can be jail for five years and a fine of Rs 10 lakhs.</li>
                                            <li>Section 67A, IT Act, 2000: It punishes sharing material containing sexually explicit act in electronic form with jail for seven years and a fine of Rs 10 lakhs.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>The provisions of the Information Technology Act are not gender specific and apply to everyone.</li>
                        </ol>
                    </li>
                    <li>
                        <h4 className="text-cyan lg:text-2xl md:text-2xl text-xl font-medium py-4">Reporting</h4>
                        <p>While it is important that you do not commit or cause to commit an act prohibited under this Minor and Learner Interaction Guidelines and any applicable laws relating to Child Abuse, it is also very important that they do not remain bystanders when they encounter online abuse and exploitation. In fact, being aware of a child abuse case and not reporting it is illegal under the POCSO Act, 2012.</p>
                        <p>In the event you suspect any form of Child Abuse from your interaction with the Minor Learner, then you must write to <a href='#' className='text-cyan'>support@brainzeo.co</a> so that the necessary actions can be taken by the Company.</p>
                    </li>
                </ol>
            </div>
        </div>
    );
}

export default Code;
